In [ ]:
#prepare a model for prediction of house prices by using l1 and l2 regression

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
df=pd.read_csv('housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [ ]:
df['ocean_proximity'].nunique()

5

In [ ]:
df['ocean_proximity']=df.groupby('ocean_proximity')['median_house_value'].transform('mean')

In [ ]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  ocean_proximity  
0       322.0       126.0         8.3252            452600.0     259212.31179  
1      2401.0      1138.0         8.3014            358500.0     259212.31179  
2       496.0       177.0         7.2574            352100.0     259212.31179  
3       558.0       219.0         5.6431            341300.0     259212.31179  
4       565.0       259.0         3.8462            342200.0     259212.31179

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df1=pd.DataFrame(scaler.fit_transform(df),columns=df.columns)
df1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       0.211155  0.567481            0.784314     0.022331        0.019863   
1       0.212151  0.565356            0.392157     0.180503        0.171477   
2       0.210159  0.564293            1.000000     0.037260        0.029330   
3       0.209163  0.564293            1.000000     0.032352        0.036313   
4       0.209163  0.564293            1.000000     0.041330        0.043296   
...          ...       ...                 ...          ...             ...   
20635   0.324701  0.737513            0.470588     0.042296        0.057883   
20636   0.312749  0.738576            0.333333     0.017676        0.023122   
20637   0.311753  0.732200            0.313725     0.057277        0.075109   
20638   0.301793  0.732200            0.333333     0.047256        0.063315   
20639   0.309761  0.725824            0.294118     0.070782        0.095438   

       population  households  median_income  median_house_value  \
0        0.008941    0.020556       0.539668            0.902266   
1        0.067210    0.186976       0.538027            0.708247   
2        0.013818    0.028943       0.466028            0.695051   
3        0.015555    0.035849       0.354699            0.672783   
4        0.015752    0.042427       0.230776            0.674638   
...           ...         ...            ...                 ...   
20635    0.023599    0.054103       0.073130            0.130105   
20636    0.009894    0.018582       0.141853            0.128043   
20637    0.028140    0.071041       0.082764            0.159383   
20638    0.020684    0.057227       0.094295            0.143713   
20639    0.038790    0.086992       0.130253            0.153403   

       ocean_proximity  
0             0.525777  
1             0.525777  
2             0.525777  
3             0.525777  
4             0.525777  
...                ...  
20635         0.000000  
20636         0.000000  
20637         0.000000  
20638         0.000000  
20639         0.000000  

[20640 rows x 10 columns]

In [ ]:
y=df1['median_house_value']
x=df1.drop('median_house_value',axis=1)
y.shape,x.shape

((20640,), (20640, 9))

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((14448, 9), (6192, 9), (14448,), (6192,))

In [ ]:
x_train.fillna(999, inplace=True)
#fillna is used to fill the null vaues with provided values
#inplace=True means that changes will be permanent.

In [ ]:
model=LinearRegression()
lasso_model=Lasso(alpha=0.1)
ridge_model=Ridge(alpha=0.1)
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.1)

In [ ]:
ridge_model.fit(x_train,y_train)

Ridge(alpha=0.1)

In [ ]:
model.coef_

array([-5.21369632e-01, -4.80885402e-01,  1.05448058e-01, -9.95155295e-02,
        9.05811317e-07, -2.96900236e+00,  1.71684723e+00,  1.14140894e+00,
        1.78608947e-01])

In [ ]:
lasso_model.coef_

array([-0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.])

In [ ]:
ridge_model.coef_

array([-5.19071574e-01, -4.77794156e-01,  1.05589015e-01, -8.48795182e-02,
        8.27450951e-07, -2.83592891e+00,  1.64191665e+00,  1.13973254e+00,
        1.80420220e-01])

In [ ]:
model.intercept_

0.40752917375286374

In [ ]:
lasso_model.intercept_

0.3972234099154518

In [ ]:
ridge_model.intercept_

0.4050122758456162